### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by aaron-em** [benrady/shinatra#6]
Out of date documentation. Works fine under Cygwin. Example:

![shinatra cygwin](https://cloud.githubusercontent.com/assets/5650970/20276046/abba1dfe-aa68-11e6-9ea8-6b915e2dc0ee.PNG)

**Comment by skibz** [comment]
i figured this would work just fine under cygwin or even the windows subsystem for linux

**Comment by benrady** [comment]
Duplicate of #2
